# Generated by Django 3.2.7 on 2022-12-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=200)),
                ('post_data', models.DateField(auto_now_add=True)),
                ('times', models.IntegerField(default=0)),
                ('respondent', models.IntegerField(default=0)),
            ],
        ),
    ]
